version: '2'

services:
    coordinator:
        container_name: coordinator
        env_file:
          - .env
          - .secret.env
        build:
            context: .
            dockerfile: ./docker/Dockerfile.coord
            args:
                FLAVOR:
                ARCH: ${ARCH}
                BIND_ADDR: 10.1.0.2
                BIND_PORT: 4001

        expose: ["4000-4099"]
        networks:
          mesh:
            ipv4_address: 10.1.0.2

    peer1:
        container_name: peer1
        env_file:
          - .env
          - .secret.env
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                FLAVOR:
                ARCH: ${ARCH}
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                BIND_PORT: 5100
                DEVICE_NAME: peer1
        expose: ["5100-5109"]
        networks:
          - mesh

    peer2:
        container_name: peer2
        env_file:
          - .env
          - .secret.env
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                FLAVOR:
                ARCH: ${ARCH}
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                BIND_PORT: 5110
                DEVICE_NAME: peer2
        expose: ["5110-5119"]
        networks:
          - mesh

networks:
    mesh:
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.0.0/16
                  gateway: 10.1.0.1
                  # keep static IPs from clashing w/ assigned
                  ip_range: 10.1.1.0/24

