version: '2'

services:
    coordinator:
        container_name: coordinator
        build:
            context: .
            dockerfile: ./docker/Dockerfile.coord
            args:
                FLAVOR:
                BIND_ADDR: 10.1.0.2
                BIND_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"

        expose: ["4000-4099"]
#       ports:
#          - "4000-4099:4000-4099"
        networks:
            mesh:
                ipv4_address: 10.1.0.2

    peer1:
        container_name: peer1
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                DEVICE_NAME: "peer1"
                FLAVOR:
                BIND_PORT: 5101
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"
                    #        expose: ["5100-5199"]
#       ports:
#           - "4100-4199:4100-4199"
        networks:
            - mesh

    # XXX copy-pasta peers for testing, should probably just script it.
    peer2:
        container_name: peer2
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                DEVICE_NAME: "peer2"
                FLAVOR:
                BIND_PORT: 5102
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"
                    #        expose: ["5100-5199"]
#       ports:
#           - "4100-4199:4100-4199"
        networks:
            - mesh
    peer3:
        container_name: peer3
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                DEVICE_NAME: "peer3"
                FLAVOR:
                BIND_PORT: 5103
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"
                    #        expose: ["4100-4199"]
#       ports:
#           - "4100-4199:4100-4199"
        networks:
            - mesh

networks:
    mesh:
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.0.0/16
                  gateway: 10.1.0.1

