version: '2'

services:
    coordinator:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.coord
            args:
                FLAVOR:
                BIND_ADDR: 10.1.0.2
                BIND_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"

        ports:
            - "4000-4099:4000-4099"
        networks:
            - mesh

    # XXX copy-pasta peers for testing, should probably just script it.
    peer1:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.peer
            args:
                FLAVOR:
                BIND_ADDR: 0.0.0.0
                BIND_PORT: 4001
                COORD_ADDR: 10.1.0.2
                COORD_PORT: 4001
                DITTO_APP_ID: "${DITTO_APP_ID}"
                DITTO_PG_TOKEN: "${DITTO_PG_TOKEN}"
                DITTO_LICENSE: "${DITTO_LICENSE}"
        ports:
            - "4000-4099:4000-4099"
        networks:
            - mesh

networks:
    mesh:
        driver: bridge
        ipam:
            config:
                - subnet: 10.1.0.0/16
                  gateway: 10.1.0.1

