[toolchain]
#channel = "nightly"
channel = "1.66.1"
#channel = "1.73.0"
components = [ "rustc-dev", "rust-analyzer" ]
profile = "minimal"
#channel = "stable"
#
# Use latest for rustfmt
#channel = "nightly"
#components = [ "rustfmt" ]
#profile = "minimal"
