#!/usr/bin/env bash
set -euo pipefail

# XXX work in progress
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# config
ARCH=${ARCH:-x86_64-unknown-linux-gnu}
FLAVOR=${FLAVOR:-debug}

COORD_PORT=4001
COORD_ADDR="10.1.0.2"
PEER_BEGIN_PORT=5100
IP_RANGE="10.1.1.0/24"
SUBNET="10.1.0.0/16"
GATEWAY="10.1.0.1"

usage() {
    echo "Usage: $0 build | stop | run <scale-factor> | clean | watch"
    echo "  ARCH=$ARCH      FLAVOR=$FLAVOR"
    exit 1
}

build_coord() {
    # take all args
    local build_args="$1"

    pre='docker build '
    post=' -t cmesh-coord -f docker/Dockerfile.coord .'
    eval "$pre" "$build_args" "$post"
}

build_peer() {
    local build_args="$1"
    # build and run peer container
    eval 'docker build' "$build_args" '-t cmesh-peer -f docker/Dockerfile.peer .'
}

run_coord() {
    local scale=$1
    set -x
    docker run -d --rm --name cmesh-coord --label cmesh \
      --network=mesh --ip=$COORD_ADDR \
    cmesh-coord --bind-addr $COORD_ADDR --bind-port $COORD_PORT --min-peers $scale
    set +x
}

stop_coord() {
    cs=$(docker ps -q -f ancestor=cmesh-coord)
    if [[ -n $cs ]]; then
        docker stop $cs
    fi
}

run_peer() {
    local i=$1
    local beginport=$2
    local endport=$3
    set -x
    docker run -d --rm --name cmesh-peer-$i --label cmesh \
      --network=mesh --expose "$beginport-$endport" \
      -v peer-output:/output \
    cmesh-peer --coord-addr $COORD_ADDR --coord-port $COORD_PORT \
      --bind-port $beginport --output-dir=/output --device-name peer$i
    set +x
  }


run_peers() {
    local scale=$1
    PARALLEL=
    if [[ -n $PARALLEL ]]; then
        export -f run_peer
        time parallel -j 8 'startport=$((5100 + ( {} * 10 ) )); endport=$((startport + 9)); ' \
            'run_peer {} $startport $endport'  ::: \
          $(seq 0 $((scale - 1)))
    else
        block_sz=10
        for (( i = 0; i<scale; i++ )); do
            beginport=$((5100 + ( i * block_sz) ))
            endport=$((beginport + block_sz - 1))
            run_peer $i $beginport $endport
        done
    fi
}

stop_peers() {
    cs=$(docker ps -q -f ancestor=cmesh-peer)
    if [[ -n $cs ]]; then
        docker stop $cs
    fi
}

do_run() {
    local scale=$1
    # create bridge network "mesh"
    docker network inspect mesh >/dev/null 2>&1 || \
    docker network create -d bridge \
      --ip-range $IP_RANGE --subnet $SUBNET --gateway $GATEWAY \
      mesh
    run_coord $scale
    run_peers $scale
    volpath=$(docker volume inspect peer-output -f '{{.Mountpoint}}')
    echo "*** Peer output will be in $volpath ***"
}

do_stop() {
    stop_peers || true
    stop_coord || true
    docker network rm mesh
}

do_build() {
    local arch=$1
    local flavor=$2
    # main
    build_args="--build-arg ARCH=$arch"

    if [[ $flavor = "debug" ]]; then
        build_args+=" --build-arg FLAVOR=debug"
    fi
    echo "--> build coordinator"
    build_coord "$build_args"
    echo "--> build peer"
    build_peer "$build_args"
}

do_clean() {
    do_stop
    # clean up docker disk space
    docker system prune -f
    docker volume rm peer-output || true
}

do_watch() {
    cids=$(docker ps -q -f label=cmesh)
    if [[ -z $cids ]]; then
        echo "No cmesh containers running"
        exit 1
    fi
    cleanup()
    {
        kill "${pids[@]}" 2>/dev/null || true
    }

    trap cleanup EXIT

    for cid in ${cids[@]}; do
        echo "--> watching $cid"
        (docker logs -f -t --tail=10 "$cid" | sed -e "s/^/$cid: /")&
        pids+=($!)
        echo pids: ${pids[@]}
    done
    wait
}

# === main ===

# parse cli args
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    run)
      MODE=run
      if [ -z ${2+x} ] || [[ ! $2 =~ ^-?[0-9]+$ ]]; then
            echo "** Missing scale parameter **"
            usage
      fi
      SCALE=$2
      shift; shift
      ;;
    build)
      MODE=build
      shift # past value
      ;;
    stop)
      MODE=stop
      shift # past argument
      ;;
    clean)
      MODE=clean
      shift # past argument
      ;;
    watch)
      MODE=watch
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ -z ${MODE+x} ] ; then usage; fi

if [[ $MODE == "run" ]]; then
    do_run $SCALE
elif [[ $MODE == "stop" ]]; then
    do_stop
elif [[ $MODE == "build" ]]; then
    do_build $ARCH $FLAVOR
elif [[ $MODE == "clean" ]]; then
    do_clean
elif [[ $MODE == "watch" ]]; then
    do_watch
fi
