[package]
name = "cmesh-coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
clap = { version = "=4.2.0", features = ["derive"] }
chrono = "0.4.31"
dittolive-ditto = { version = "4.5.2" }
env_logger = "0.10.1"
log = "0.4.20"

